
name: Build Maven project

on: [push, pull_request, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          java-version: '13'
          distribution: 'adopt'
          
      - name: Starting Docker for database
        run: docker-compose up -d 
        
      - name: Build with Maven
        run: mvn clean verify
